const data = [
  {
    id: "1",
    image: "",
    name: "Pizza Town",
    desc: "Pizzas, Italian, Pastas, Deserts",
    isPureVeg: false,
    rating: "2",
    deliveryTime: "20 MIN",
    cost: "400",
    offer: "WELCOME 50",
    location: "Kalyan, Thane",
    timing: "10:00 AM - 10:00 PM",
    menuData: [
      {
        menuId: "menu1",
        menuImg: require("./images/pizza3.jpg"),
        menuName: "Golden Corn Pizza",
        price: "100",
        menuRating: "4",
        menuType: "veg",
        menuCategory: ["veg", "Pizza Mania"],
      },
      {
        menuId: "menu2",
        menuImg: require("./images/pizza3.jpg"),
        menuName: "Panner Pizza",
        price: "120",
        menuRating: "4",
        menuType: "veg",
        menuCategory: ["veg", "Pizza Mania"],
      },
      {
        menuId: "menu3",
        menuImg: require("./images/pizza5.jpg"),
        menuName: "Margerita Pizza",
        price: "140",
        menuRating: "5",
        menuType: "veg",
        menuCategory: ["veg", "Pizza Mania"],
      },
      {
        menuId: "menu4",
        menuImg: require("./images/pizza3.jpg"),
        menuName: "Capsicum Pizza",
        price: "90",
        menuRating: "2",
        menuType: "veg",
        menuCategory: ["veg", "Pizza Mania"],
      },
      {
        menuId: "menu5",
        menuImg: require("./images/pizza3.jpg"),
        menuName: "Chiken Kheema Pizza",
        price: "200",
        menuRating: "4",
        menuType: "non-veg",
        menuCategory: ["non-veg", "Pizza Mania"],
      },
      {
        menuId: "menu6",
        menuImg: require("./images/pizza4.jpg"),
        menuName: "Butter Chicken Pizza",
        price: "300",
        menuRating: "5",
        menuType: "non-veg",
        menuCategory: ["non-veg", "Pizza Mania"],
      },
      {
        menuId: "menu7",
        menuImg: require("./images/coca-cola.jpg"),
        menuName: "Coca Cola 500ml",
        price: "50",
        menuRating: "5",
        menuType: "veg",
        menuCategory: ["veg", "drinks"],
      },
      {
        menuId: "menu8",
        menuImg: require("./images/softy.jpg"),
        menuName: "Softy",
        price: "120",
        menuRating: "4",
        menuType: "veg",
        menuCategory: ["veg", "dessert"],
      },
      {
        menuId: "menu9",
        menuImg: require("./images/ice-cream1.jpg"),
        menuName: "Ice-Cream",
        price: "40",
        menuRating: "4",
        menuType: "veg",
        menuCategory: ["veg", "dessert"],
      },
    ],
  },
];
export default data;
